version: "3.9"

services:
  node:
    image: node:16-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env

  redis:
    image: redis:6-alpine

  nginx:
    build: .docker/nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
      - ./runtime/logs/nginx:/var/log/nginx
    links:
      - php
      - imgproxy
      - s3
      - redis

  php:
    build: .docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    links:
      - mysql
      - redis
      - s3

  s3:
    image: minio/minio
    volumes:
      - ./runtime/minio:/data
    env_file:
      - .env
    command: minio server --console-address :9090 --address :9000 /data

  imgproxy:
    image: darthsim/imgproxy
    env_file:
      - .env
    links:
      - s3
    volumes:
      - .:/var/www

  mysql:
    image: mysql:8
    volumes:
      - ./.docker/mysql:/etc/mysql/conf.d
      - ./runtime/logs/mysql:/var/log/mysql
      - ./runtime/mysql:/var/lib/mysql
      - ./runtime/mysql-files:/var/lib/mysql-files
      - .:/var/www
      - ./runtime:/docker-entrypoint-initdb.d
    env_file:
      - .env
