#!/usr/bin/env php
<?php

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'rb'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'wb'));

require(__DIR__ . '/common/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/console/config/main.php'),
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
