---
- name: Generate .env
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ ansistrano_release_path.stdout }}/.env"
    mode: 0664

- name: Generate nginx config
  ansible.builtin.template:
    src: "{{ nginx_config_template }}"
    dest: /etc/nginx/sites-enabled/market
    mode: 0644
  become: true
