---
- hosts:
    - stage
  vars:
    # ansistrano_deploy_from: "../build.tar.gz" # Where my local project is (relative or absolute path)
    ansistrano_deploy_to: "/var/www/market" # Base path to deploy to.
    ansistrano_version_dir: "releases" # Releases folder name
    ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
    ansistrano_current_via: "symlink" # Deployment strategy who code should be deployed to current path. Options are symlink or rsync
    ansistrano_keep_releases: 3 # Releases to keep after a new deployment. See "Pruning old releases".
    ansistrano_allow_anonymous_stats: false
    ansistrano_deploy_via: s3_unarchive
    ansistrano_s3_rgw: true # must be Ansible >= 2.2. use Ceph RGW for S3 compatible cloud providers
    ansistrano_s3_ignore_nonexistent_bucket: false
    # ansistrano_s3_bucket: s3bucket
    # ansistrano_s3_object: s3object.tgz # Add the _unarchive suffix to the ansistrano_deploy_via if your object is a package (ie: s3_unarchive)
    # ansistrano_s3_region: eu-west-1
    # ansistrano_s3_url: http://rgw.example.com # when use Ceph RGW, set url
    # Optional variables, omitted by default
    # ansistrano_s3_aws_access_key: YOUR_AWS_ACCESS_KEY
    # ansistrano_s3_aws_secret_key: YOUR_AWS_SECRET_KEY
    ansistrano_before_symlink_tasks_file: tasks/before_symlink.yml
    ansistrano_after_symlink_tasks_file: tasks/after_symlink.yml
    ansistrano_shared_paths:
      - runtime
      - storage
      - admin/web/.well-known
    # project_version: "{{ lookup('ansible.builtin.env', 'GITHUB_SHA') }}"
    # nginx_config_template: nginx.stage.conf.j2
  roles:
    - { role: ansistrano.deploy }
